run:
  timeout: 5m
  tests: false
  build-tags:
    - integration

linters-settings:
  govet:
    enable-all: true
  gofmt:
    simplify: true
  goimports:
    local-prefixes: pr-reviewer-service
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: exported
        severity: warning

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
    - revive
    - misspell
    - unconvert
    - unparam
  disable:
    - typecheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
